export enum SpecificPermissionAction {
  UPDATE_STATUS = "UPDATE_STATUS",
  UPDATE_PICTURE = "UPDATE_PICTURE",
  EXPORT_DATA = "EXPORT_DATA",
  IMPORT_DATA = "IMPORT_DATA",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  RESET_PASSWORD = "RESET_PASSWORD"
}
